# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 03:04
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='focusArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toutiao', models.BooleanField(default=False, verbose_name='设为头条')),
                ('pic', models.ImageField(default='images/default.jpg', upload_to='uploads/top_images', verbose_name='头条图片436*200')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='清朗安全', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='清朗安全', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='focus_detail', max_length=255, verbose_name='默认网址勿改')),
            ],
            options={
                'verbose_name': '安全热点',
            },
        ),
        migrations.CreateModel(
            name='lawArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toutiao', models.BooleanField(default=False, verbose_name='设为头条')),
                ('pic', models.ImageField(default='images/default.jpg', upload_to='uploads/top_images', verbose_name='头条图片436*200')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='清朗安全', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='清朗安全', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='law_detail', max_length=255, verbose_name='默认网址勿改')),
            ],
            options={
                'verbose_name': '安全法治',
            },
        ),
        migrations.CreateModel(
            name='policyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toutiao', models.BooleanField(default=False, verbose_name='设为头条')),
                ('pic', models.ImageField(default='images/default.jpg', upload_to='uploads/top_images', verbose_name='头条图片436*200')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='清朗安全', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='清朗安全', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='policy_detail', max_length=255, verbose_name='默认网址勿改')),
            ],
            options={
                'verbose_name': '管理政策',
            },
        ),
        migrations.CreateModel(
            name='popularScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toutiao', models.BooleanField(default=False, verbose_name='设为头条')),
                ('pic', models.ImageField(default='images/default.jpg', upload_to='uploads/top_images', verbose_name='头条图片436*200')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='清朗安全', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='清朗安全', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='popular_detail', max_length=255, verbose_name='默认网址勿改')),
            ],
            options={
                'verbose_name': '趣味科普',
            },
        ),
        migrations.CreateModel(
            name='talentsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toutiao', models.BooleanField(default=False, verbose_name='设为头条')),
                ('pic', models.ImageField(default='images/default.jpg', upload_to='uploads/top_images', verbose_name='头条图片436*200')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='清朗安全', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='清朗安全', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='talents_detail', max_length=255, verbose_name='默认网址勿改')),
            ],
            options={
                'verbose_name': '人才培养',
            },
        ),
        migrations.CreateModel(
            name='techArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toutiao', models.BooleanField(default=False, verbose_name='设为头条')),
                ('pic', models.ImageField(default='images/default.jpg', upload_to='uploads/top_images', verbose_name='头条图片436*200')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='清朗安全', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='清朗安全', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='tech_detail', max_length=255, verbose_name='默认网址勿改')),
            ],
            options={
                'verbose_name': '前沿技术',
            },
        ),
    ]
