# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170318_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusarticle',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='lawarticle',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='policyarticle',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='popularscience',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='talentsarticle',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='techarticle',
            name='pic',
        ),
    ]
