# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-18 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170318_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusarticle',
            name='pic',
            field=models.ImageField(default='uploads/top_images/default.jpg', upload_to='uploads/top_images/', verbose_name='头条图片436*200'),
        ),
        migrations.AddField(
            model_name='lawarticle',
            name='pic',
            field=models.ImageField(default='uploads/top_images/default.jpg', upload_to='uploads/top_images/', verbose_name='头条图片436*200'),
        ),
        migrations.AddField(
            model_name='policyarticle',
            name='pic',
            field=models.ImageField(default='uploads/top_images/default.jpg', upload_to='uploads/top_images/', verbose_name='头条图片436*200'),
        ),
        migrations.AddField(
            model_name='popularscience',
            name='pic',
            field=models.ImageField(default='uploads/top_images/default.jpg', upload_to='uploads/top_images/', verbose_name='头条图片436*200'),
        ),
        migrations.AddField(
            model_name='talentsarticle',
            name='pic',
            field=models.ImageField(default='uploads/top_images/default.jpg', upload_to='uploads/top_images/', verbose_name='头条图片436*200'),
        ),
        migrations.AddField(
            model_name='techarticle',
            name='pic',
            field=models.ImageField(default='uploads/top_images/default.jpg', upload_to='uploads/top_images/', verbose_name='头条图片436*200'),
        ),
    ]
