# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170318_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='slideImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='图片标题')),
                ('slidepic', models.ImageField(default='uploads/top_images/slide.jpg', upload_to='uploads/top_images/', verbose_name='首页轮播图片1360*250')),
            ],
            options={
                'verbose_name': '首页轮播图片',
            },
        ),
    ]
