# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 07:36
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_policyhomeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toutiao', models.BooleanField(default=False, verbose_name='设为头条')),
                ('pic', models.ImageField(default='uploads/top_images/default.jpg', upload_to='uploads/top_images/', verbose_name='头条图片436*200')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('published', models.BooleanField(default=True, verbose_name='正式发布')),
                ('pub_date', models.DateTimeField(verbose_name='发表日期')),
                ('author', models.CharField(default='清朗安全', max_length=255, verbose_name='作者')),
                ('sourcefrom', models.CharField(default='清朗安全', max_length=255, verbose_name='来源')),
                ('slug_url', models.CharField(default='focus_detail', max_length=255, verbose_name='默认网址勿改')),
                ('slug_name', models.CharField(default='安全热点', max_length=255, verbose_name='默认栏目名勿改')),
            ],
            options={
                'verbose_name': '文章',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Categary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categary', models.CharField(default='安全热点', max_length=255, verbose_name='分类')),
                ('url', models.CharField(default='', max_length=255, verbose_name='URL')),
                ('num', models.IntegerField()),
            ],
            options={
                'verbose_name': '首页类别',
                'ordering': ['num'],
            },
        ),
        migrations.DeleteModel(
            name='focusArticle',
        ),
        migrations.DeleteModel(
            name='lawArticle',
        ),
        migrations.DeleteModel(
            name='policyArticle',
        ),
        migrations.DeleteModel(
            name='policyhomeImage',
        ),
        migrations.DeleteModel(
            name='popularScience',
        ),
        migrations.DeleteModel(
            name='talentsArticle',
        ),
        migrations.DeleteModel(
            name='techArticle',
        ),
        migrations.AddField(
            model_name='article',
            name='categary',
            field=models.ManyToManyField(to='news.Categary'),
        ),
    ]
