# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170602_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='categary',
        ),
        migrations.AddField(
            model_name='article',
            name='categary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Categary'),
            preserve_default=False,
        ),
    ]
